[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "owlhearyou"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "fastapi",
    "uvicorn",
    "websockets",
    "sounddevice",
    "numpy",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["src*"]
